name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '😼 Features'
    labels:
      - 'feature'
      - 'feat'
  - title: '👾 Bug Fixes'
    labels:
      - 'fix'
  - title: '🫥 Maintenance'
    labels:
      - 'chore'
      - 'test'
      - 'build'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes
  $CHANGES
