name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

autolabeler:
  - label: 'feat'
    title: ['/^feat(ure)?:/i']
  - label: 'bug'
    title: ['/^(fix|bug):/i']
  - label: 'security'
    title: ['/^security/i']
  - label: 'documentation'
    title: ['/^doc(s|umentation)?\b/i']
  - label: 'go'
    title: ['/^deps\(go\)/i']
  - label: 'docker'
    title: ['/^deps\(docker\)/i']
  - label: 'github-actions'
    title: ['/^deps\(actions\)/i']
  - label: 'maintenance'
    title: ['/^(chore|test|ci|refactor|enhancement|todo)/i']

categories:
  - title: 'Features'
    labels: ['feat']
  - title: 'Bug Fixes'
    labels: ['bug', 'fix']
  - title: 'Security'
    labels: ['security']
  - title: 'Dependencies'
    labels: ['dependency', 'go', 'docker', 'github-actions']
  - title: 'Docs'
    labels: ['documentation']
  - title: 'Maintenance'
    labels: ['maintenance', 'todo', 'enhancement', 'chore', 'refactor', 'ci', 'test']

exclude-labels:
  - 'WIP'
  - 'wontfix'
  - 'invalid'

version-resolver:
  major:
    labels: ['major']
  minor:
    labels: ['minor']
  patch:
    labels: ['patch']
  default: patch

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'

template: |
  ## Changes
  $CHANGES
