version: "2"

linters:
  default: none
  enable:
    - errcheck
    - staticcheck
    - govet
    - ineffassign
    - bodyclose
    - revive
    - unused
    - gocritic
    - prealloc

  settings:
    govet:
      enable:
        - shadow
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
