{
 "title": "App dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Errors Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{status=~\"5..\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS Peak",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P99 Latency Max",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{job=\"goroutine_app\"}[$__rate_interval])) by (le)) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[$__rate_interval])) by (path, method)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Latency P95 Rate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[$__rate_interval])) by (le, path, method)) * 1000",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 5, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "errors/sec" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"5..\"}[1m])) by (path, method)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Host Drive Time Spent Doing I/Os",
   "type": "timeseries",
   "description": "Percentage of time the disk spent actively processing I/O operations, including general I/O, discards (TRIM), and write cache flushes",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total[$__rate_interval])",
     "legendFormat": "{{device}} - General IO"
    },
    {
     "expr": "rate(node_disk_discard_time_seconds_total[$__rate_interval])",
     "legendFormat": "{{device}} - Discard/TRIM"
    },
    {
     "expr": "rate(node_disk_flush_requests_time_seconds_total[$__rate_interval])",
     "legendFormat": "{{device}} - Flush (write cache)"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 20 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"goroutine_app\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Core %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"goroutine_app\"}[$__rate_interval]) * 100",
     "legendFormat": "App"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) * 100",
     "legendFormat": "Host"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"goroutine_app\"} / 2^20",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Host Drive Average Queue Size",
   "type": "timeseries",
   "description": "Average queue length of the requests that were issued to the device",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_weighted_seconds_total[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "GC Pauses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum{job=\"goroutine_app\"}[$__rate_interval]) / rate(go_gc_duration_seconds_count{job=\"goroutine_app\"}[$__rate_interval]) * 1000",
     "legendFormat": "App"
    }
   ]
  },
  {
   "title": "Memory allocations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"goroutine_app\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host RAM & Swap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100",
     "legendFormat": "RAM"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes) / node_memory_SwapTotal_bytes * 100",
     "legendFormat": "Swap"
    }
   ]
  }
 ]
}