apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    basicAuth: true
    basicAuthUser: ${PROMETHEUS_USER}
    basicAuthPassword: ${PROMETHEUS_PASSWORD}
    isDefault: true
    uid: Prometheus
    jsonData:
      timeInterval: "5s"
  - name: Loki
    type: loki
    url: http://loki:3100
    uid: Loki
