// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/boards": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get many boards for the current user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "boards"
                ],
                "summary": "Get many boards",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handler.boardResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "VALIDATION_ERROR",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized: INVALID_TOKEN or INVALID_AUTH_HEADER",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpschema.Error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new board for the current user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "boards"
                ],
                "summary": "Create a new board",
                "parameters": [
                    {
                        "description": "Board details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.createBoardBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handler.boardResponse"
                        }
                    },
                    "400": {
                        "description": "VALIDATION_ERROR",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized: INVALID_TOKEN or INVALID_AUTH_HEADER",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpschema.Error"
                        }
                    }
                }
            }
        },
        "/v1/boards/{boardId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get board metadata by id for the current user (owner only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "boards"
                ],
                "summary": "Get a board by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Board ID",
                        "name": "boardId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.boardResponse"
                        }
                    },
                    "400": {
                        "description": "VALIDATION_ERROR",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized: INVALID_TOKEN or INVALID_AUTH_HEADER",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "404": {
                        "description": "NOT_FOUND",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpschema.Error"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Permanently delete a board and its columns and tasks for the current user (owner only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "boards"
                ],
                "summary": "Delete a board by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Board ID",
                        "name": "boardId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "VALIDATION_ERROR",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized: INVALID_TOKEN or INVALID_AUTH_HEADER",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "404": {
                        "description": "NOT_FOUND",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpschema.Error"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Partially update board metadata for the current user (owner only). Provided fields are updated; omitted or null fields are ignored.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "boards"
                ],
                "summary": "UpdateByID a board by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Board ID",
                        "name": "boardId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Board fields to update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.updateBoardBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.boardResponse"
                        }
                    },
                    "400": {
                        "description": "VALIDATION_ERROR",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized: INVALID_TOKEN or INVALID_AUTH_HEADER",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "404": {
                        "description": "NOT_FOUND",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpschema.Error"
                        }
                    }
                }
            }
        },
        "/v1/boards/{boardId}/aggregate": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a board with nested columns and tasks for the current user (owner only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "boards"
                ],
                "summary": "Get a board aggregate by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Board ID",
                        "name": "boardId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.aggregateBoardResponse"
                        }
                    },
                    "400": {
                        "description": "VALIDATION_ERROR",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized: INVALID_TOKEN or INVALID_AUTH_HEADER",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "404": {
                        "description": "BOARD_NOT_FOUND",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpschema.Error"
                        }
                    }
                }
            }
        },
        "/v1/boards/{boardId}/columns": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all columns belonging to the specified board, ordered by position ASC.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "columns"
                ],
                "summary": "List all columns in a board",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Board ID",
                        "name": "boardId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handler.columnResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "VALIDATION_ERROR",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized: INVALID_TOKEN or INVALID_AUTH_HEADER",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "404": {
                        "description": "BOARD_NOT_FOUND",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpschema.Error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new column in board for the current user. Column is appended to the end.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "columns"
                ],
                "summary": "Create a new column",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Board ID",
                        "name": "boardId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Column details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.createColumnBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handler.columnResponse"
                        }
                    },
                    "400": {
                        "description": "VALIDATION_ERROR",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized: INVALID_TOKEN or INVALID_AUTH_HEADER",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "404": {
                        "description": "BOARD_NOT_FOUND",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpschema.Error"
                        }
                    }
                }
            }
        },
        "/v1/boards/{boardId}/columns/{columnId}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Permanently delete a column from board for the current user and shift positions to close the gap.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "columns"
                ],
                "summary": "Delete a column by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Board ID",
                        "name": "boardId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Column ID",
                        "name": "columnId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "VALIDATION_ERROR",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized: INVALID_TOKEN or INVALID_AUTH_HEADER",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "404": {
                        "description": "COLUMN_NOT_FOUND",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpschema.Error"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Partially update column metadata for the current user. Provided fields are updated; omitted or null fields are ignored.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "columns"
                ],
                "summary": "Rename a column by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Board ID",
                        "name": "boardId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Column ID",
                        "name": "columnId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Column fields to update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.updateColumnBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.columnResponse"
                        }
                    },
                    "400": {
                        "description": "VALIDATION_ERROR",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized: INVALID_TOKEN or INVALID_AUTH_HEADER",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "404": {
                        "description": "COLUMN_NOT_FOUND",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpschema.Error"
                        }
                    }
                }
            }
        },
        "/v1/boards/{boardId}/columns/{columnId}/position": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Move a column within a board for the current user and shift neighboring columns accordingly.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "columns"
                ],
                "summary": "Move a column to a new position",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Board ID",
                        "name": "boardId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Column ID",
                        "name": "columnId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Target position",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.moveColumnBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.columnPositionResponse"
                        }
                    },
                    "400": {
                        "description": "VALIDATION_ERROR",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized: INVALID_TOKEN or INVALID_AUTH_HEADER",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "404": {
                        "description": "COLUMN_NOT_FOUND",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpschema.Error"
                        }
                    }
                }
            }
        },
        "/v1/boards/{boardId}/columns/{columnId}/tasks": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all tasks belonging to the specified column, ordered by position ASC.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "List all tasks in a column",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Board ID",
                        "name": "boardId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Column ID",
                        "name": "columnId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handler.taskResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "VALIDATION_ERROR",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized: INVALID_TOKEN or INVALID_AUTH_HEADER",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "404": {
                        "description": "COLUMN_NOT_FOUND",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpschema.Error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new task in a column for the current user. Task is appended to the end of the column.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Create a new task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Board ID",
                        "name": "boardId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Column ID",
                        "name": "columnId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Task details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.createTaskBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handler.taskResponse"
                        }
                    },
                    "400": {
                        "description": "VALIDATION_ERROR",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized: INVALID_TOKEN or INVALID_AUTH_HEADER",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "404": {
                        "description": "COLUMN_NOT_FOUND",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpschema.Error"
                        }
                    }
                }
            }
        },
        "/v1/boards/{boardId}/columns/{columnId}/tasks/{taskId}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Permanently delete a task from a column for the current user and shift positions to close the gap.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Delete a task by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Board ID",
                        "name": "boardId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Column ID",
                        "name": "columnId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "taskId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "VALIDATION_ERROR",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized: INVALID_TOKEN or INVALID_AUTH_HEADER",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "404": {
                        "description": "TASK_NOT_FOUND",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpschema.Error"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Partially update task metadata for the current user. Provided fields are updated; omitted or null fields are ignored.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Update a task by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Board ID",
                        "name": "boardId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Column ID",
                        "name": "columnId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "taskId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Task fields to update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.updateTaskBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.taskResponse"
                        }
                    },
                    "400": {
                        "description": "VALIDATION_ERROR",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized: INVALID_TOKEN or INVALID_AUTH_HEADER",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "404": {
                        "description": "TASK_NOT_FOUND",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpschema.Error"
                        }
                    }
                }
            }
        },
        "/v1/boards/{boardId}/columns/{columnId}/tasks/{taskId}/position": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Move a task within its column or across columns in the same board and shift neighboring tasks accordingly.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Move a task to a new position, possibly to another column",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Board ID",
                        "name": "boardId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Column ID",
                        "name": "columnId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "taskId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Target column and position",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.moveTaskBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.taskPositionResponse"
                        }
                    },
                    "400": {
                        "description": "VALIDATION_ERROR",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized: INVALID_TOKEN or INVALID_AUTH_HEADER",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "404": {
                        "description": "TASK_NOT_FOUND or COLUMN_NOT_FOUND",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpschema.Error"
                        }
                    }
                }
            }
        },
        "/v1/health": {
            "get": {
                "description": "Check if the server is alive",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpschema.Status"
                        }
                    }
                }
            }
        },
        "/v1/login": {
            "post": {
                "description": "Login with email and password to get a JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login a user",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.loginBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.loginResponse"
                        }
                    },
                    "400": {
                        "description": "VALIDATION_ERROR",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "401": {
                        "description": "INVALID_CREDENTIALS or USER_NOT_FOUND",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpschema.Error"
                        }
                    }
                }
            }
        },
        "/v1/register": {
            "post": {
                "description": "Register a new user with email and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Registration details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.registerBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpschema.Status"
                        }
                    },
                    "400": {
                        "description": "VALIDATION_ERROR",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "409": {
                        "description": "USER_ALREADY_EXISTS",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpschema.Error"
                        }
                    }
                }
            }
        },
        "/v1/whoami": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get current user ID from token. This is a protected endpoint — in addition to the responses listed below, the auth middleware may return 401 with codes INVALID_AUTH_HEADER or INVALID_TOKEN.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get current user info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.whoAmIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized: INVALID_TOKEN (handler) or INVALID_AUTH_HEADER / INVALID_TOKEN (auth middleware)",
                        "schema": {
                            "$ref": "#/definitions/httpschema.DetailedError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/httpschema.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.aggregateBoardResponse": {
            "type": "object",
            "properties": {
                "columns": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.aggregateColumnResponse"
                    }
                },
                "createdAt": {
                    "type": "string",
                    "example": "2026-03-07T20:56:50.000+03:00"
                },
                "description": {
                    "type": "string",
                    "example": "My Todo Description"
                },
                "id": {
                    "type": "string",
                    "example": "019cc971-e5be-7df9-ae8a-c6e3f29c86a2"
                },
                "name": {
                    "type": "string",
                    "example": "My Todo Name"
                },
                "ownerId": {
                    "type": "string",
                    "example": "019cc971-e5be-7df9-ae8a-c6e3f29c86a2"
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2026-03-07T20:56:50.000+03:00"
                }
            }
        },
        "handler.aggregateColumnResponse": {
            "type": "object",
            "properties": {
                "boardId": {
                    "type": "string",
                    "example": "019cc971-e5be-7df9-ae8a-c6e3f29c86a1"
                },
                "createdAt": {
                    "type": "string",
                    "example": "2026-03-07T20:56:50.000+03:00"
                },
                "id": {
                    "type": "string",
                    "example": "019cc971-e5be-7df9-ae8a-c6e3f29c86a2"
                },
                "name": {
                    "type": "string",
                    "example": "In Progress"
                },
                "position": {
                    "type": "integer",
                    "example": 1
                },
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.taskResponse"
                    }
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2026-03-07T20:56:50.000+03:00"
                }
            }
        },
        "handler.boardResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string",
                    "example": "2026-03-07T20:56:50.000+03:00"
                },
                "description": {
                    "type": "string",
                    "example": "My Todo Description"
                },
                "id": {
                    "type": "string",
                    "example": "019cc971-e5be-7df9-ae8a-c6e3f29c86a2"
                },
                "name": {
                    "type": "string",
                    "example": "My Todo Name"
                },
                "ownerId": {
                    "type": "string",
                    "example": "019cc971-e5be-7df9-ae8a-c6e3f29c86a2"
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2026-03-07T20:56:50.000+03:00"
                }
            }
        },
        "handler.columnPositionResponse": {
            "type": "object",
            "properties": {
                "position": {
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "handler.columnResponse": {
            "type": "object",
            "properties": {
                "boardId": {
                    "type": "string",
                    "example": "019cc971-e5be-7df9-ae8a-c6e3f29c86a1"
                },
                "createdAt": {
                    "type": "string",
                    "example": "2026-03-07T20:56:50.000+03:00"
                },
                "id": {
                    "type": "string",
                    "example": "019cc971-e5be-7df9-ae8a-c6e3f29c86a2"
                },
                "name": {
                    "type": "string",
                    "example": "In Progress"
                },
                "position": {
                    "type": "integer",
                    "example": 1
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2026-03-07T20:56:50.000+03:00"
                }
            }
        },
        "handler.createBoardBody": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "My Board Description"
                },
                "name": {
                    "type": "string",
                    "example": "My Board Name"
                }
            }
        },
        "handler.createColumnBody": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "To Do"
                }
            }
        },
        "handler.createTaskBody": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Cover the new endpoint with tests"
                },
                "name": {
                    "type": "string",
                    "example": "Write tests"
                }
            }
        },
        "handler.loginBody": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "secret-password"
                }
            }
        },
        "handler.loginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "jwt-token"
                }
            }
        },
        "handler.moveColumnBody": {
            "type": "object",
            "properties": {
                "targetPosition": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "handler.moveTaskBody": {
            "type": "object",
            "properties": {
                "targetColumnId": {
                    "type": "string",
                    "example": "019cc971-e5be-7df9-ae8a-c6e3f29c86a2"
                },
                "targetPosition": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "handler.registerBody": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "secret-password"
                }
            }
        },
        "handler.taskPositionResponse": {
            "type": "object",
            "properties": {
                "columnId": {
                    "type": "string",
                    "example": "019cc971-e5be-7df9-ae8a-c6e3f29c86a2"
                },
                "position": {
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "handler.taskResponse": {
            "type": "object",
            "properties": {
                "columnId": {
                    "type": "string",
                    "example": "019cc971-e5be-7df9-ae8a-c6e3f29c86a2"
                },
                "createdAt": {
                    "type": "string",
                    "example": "2026-03-07T20:56:50.000+03:00"
                },
                "description": {
                    "type": "string",
                    "example": "Cover the new endpoint with tests"
                },
                "id": {
                    "type": "string",
                    "example": "019cc971-e5be-7df9-ae8a-c6e3f29c86a3"
                },
                "name": {
                    "type": "string",
                    "example": "Write tests"
                },
                "position": {
                    "type": "integer",
                    "example": 1
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2026-03-07T20:56:50.000+03:00"
                }
            }
        },
        "handler.updateBoardBody": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "My Board Description"
                },
                "name": {
                    "type": "string",
                    "example": "My Board Name"
                }
            }
        },
        "handler.updateColumnBody": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "In Progress"
                }
            }
        },
        "handler.updateTaskBody": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Cover edge cases"
                },
                "name": {
                    "type": "string",
                    "example": "Rewrite tests"
                }
            }
        },
        "handler.whoAmIResponse": {
            "type": "object",
            "properties": {
                "uid": {
                    "type": "string",
                    "example": "018e1000-0000-7000-8000-000000000000"
                }
            }
        },
        "httpschema.Detail": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string",
                    "example": "email"
                },
                "issues": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "must be a valid email",
                        "too short"
                    ]
                }
            }
        },
        "httpschema.DetailedError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "INVALID_CREDENTIALS"
                },
                "details": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/httpschema.Detail"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Invalid login or password"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2026-03-02T15:04:05.123Z"
                }
            }
        },
        "httpschema.Error": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "INVALID_CREDENTIALS"
                },
                "message": {
                    "type": "string",
                    "example": "Invalid login or password"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2026-03-02T15:04:05.123Z"
                }
            }
        },
        "httpschema.Status": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Enter JWT token with ` + "`" + `Bearer ` + "`" + ` prefix, e.g. ` + "`" + `Bearer eyJhbGciOi...` + "`" + `",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Goroutine kanban API",
	Description:      "A nice kanban board with a beautiful heart ✨",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
