name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

# Override default permissions
permissions:
  contents: read # To read release drafter config

jobs:
  auto-label:
    if: github.event_name == 'pull_request_target'
    permissions:
      pull-requests: write # To add labels
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter/autolabeler@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-release-draft:
    if: github.event_name == 'push'
    permissions:
      contents: write # To write drafts
      pull-requests: read # To collect metadata
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
